### ISSUE TITLE
[Not an Issue] Question regarding Blind Engine direct control

### ISSUE THREAD

**Issue by fiveseven808** [eavanvalkenburg/brunt-api#1]
I can't figure out how to get in touch with people via github, so I'll do it via issue. First off, thanks so much for porting that api to python! 

I have a big question though: 
I can't seem to pair my Blind Engine to my wifi... I lack the skills and tools necessary to see what the app is doing when communicating with the Blind Engine itself, so I can't figure out how to join the Blind Engine to get started in the first place!

You wouldn't happen to know anything about how the pairing/wifi joining part works would you by any chance?

Thanks again!

**Comment by eavanvalkenburg** [comment]
Hi, first off, no problem, I was really looking for this myself and despite a limited skillset was able to do this, but I have not looked at the registering piece and judging from the way that goes through the app I think it would be quite a challenge to do that (with connecting your phone to the Wifi network the blind puts out etc). I also did not do the tracing of calls myself, I relied on the mentioned node package for building this and am working on a home assistant component based on this package.
