### ISSUE TITLE
Failed to establish new connection; connection refused[error 13]

### ISSUE THREAD

**Issue by al3x1337** [eavanvalkenburg/brunt-api#2]
Sorry if this wasn't the right place to post in the first place, Im new to Github.

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sky.brunt.co', port=443): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10d36b748>: Failed to establish a new connection: [Errno 13] Permission denied',))`

I don't know if there's a problem with the API but i keep get a connection refused error and im sure my login credentials are correct. Was hoping if anyone has been through this and knows how to steer me in the right direction?

**Comment by eavanvalkenburg** [comment]
Hi, I don't have any issues with it, working normally for me. Are you trying a lot of calls because it seems that it is rejecting because of max tries, which could be ddos protection of the endpoint...

**Comment by al3x1337** [comment]
I shouldn't be. I tried with 2 different IPs, 2 different accounts and still the same error. 

Maybe my process isn't correct since I'm just learning python and programming but I have your files in the same folders along with MattJeanes's API and am not getting any importing errors.

**Next here is my my script:** 
`
from brunt import BruntAPI

bapi = BruntAPI()
print("Calling Brunt")

bapi.login('MYEMAIL', 'MYPASSWORD!!')
print("    Logged in, gettings things.")

`

**Followed by my error:**
`/usr/local/bin/python3.6 "/Users/al3xmac/Desktop/Python/brunt-api-master 2/brunt/brunt-api-master 3/alex.py"
Calling Brunt
Traceback (most recent call last):
  File "/Users/al3xmac/Desktop/Python/brunt-api-master 2/brunt/brunt-api-master 3/alex.py", line 6, in <module>
    bapi.login('MYEMAIL, 'MYPASSWORD')
  File "/Users/al3xmac/Desktop/Python/brunt-api-master 2/brunt/brunt-api-master 3/brunt.py", line 104, in login
    return self._login()
  File "/Users/al3xmac/Desktop/Python/brunt-api-master 2/brunt/brunt-api-master 3/brunt.py", line 117, in _login
    resp = self._http.request(data, RequestTypes.POST)
  File "/Users/al3xmac/Desktop/Python/brunt-api-master 2/brunt/brunt-api-master 3/brunt.py", line 55, in request
    resp.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sky.brunt.co/session

Process finished with exit code 1
`

It seemed my error lies in sky.brunt.co/session being invalid or it being down/refused?

**Comment by eavanvalkenburg** [comment]
Hi, please give this a try (this is a test script that I use and just tested again and it works):

```python
from brunt.brunt import BruntAPI
import json

def main():
    """ """ 
    creds=json.loads(open("creds.json").read())
    bapi = BruntAPI()
    print("Calling Brunt")
    bapi.login(creds['username'], creds['password'])
    print("    Logged in, gettings things.")
    things = bapi.getThings()
    print(f"    { len(things) } thing(s) found.")
    state = bapi.getState('Blind')
    print(state)
    print(f"    Current status of { state['NAME'] } is position { state['currentPosition'] }")
    newPos = 100
    if int(state['currentPosition']) == 100:
        newPos = 90
    print(f"    Setting { state['NAME'] } to position { newPos }")
    res = bapi.changePosition('Blind', newPos)
    print('    Success!' if res else '    Fail!')
    
if __name__ == '__main__':
    main()
```

with creds.json in the same folder:
```json
{ "username": "<email>", "password": "<password>"}
```

Please see if that works for you and then you can start comparing to see where your code differs and what it might be!
